import { Metadata } from "next";
import FilterPage from "./components/FilterPage";
import { Suspense } from "react";
import SkeletonBox from "../components/SkeletonBox";

export const metadata: Metadata = {
  title: "Produtos",
  description: "Generated by create next app",
};

export default function Products() {
  return (
    <section>
      <main>
        <Suspense fallback={<SkeletonBox />}>
          <FilterPage />
        </Suspense>
      </main>
    </section>
  );
}
