import { Metadata } from "next";
import FilterPage from "./components/FilterPage";

export const metadata: Metadata = {
  title: "Produtos",
  description: "Generated by create next app",
};

export default function Products() {
  return (
    <section>
      <main>
        <FilterPage />
      </main>
    </section>
  );
}
